version: '3.8'
services:
  yolov8_env:
    build: .
    container_name: yolov8_container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./workspace:/workspace
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    command: /bin/bash
